💡 Multi-Language Setting
KDG-Develop-Hub/social-mobile pull request #10
Opened 2024-06-07 15:12 UTC by aoiorio

## 対応したこと
- I added two json files that are for multi-language setting
- One of it is for Japanese, and the other is for English

## 対応 Issue
#9 

## 関連資料
[For setting json files](https://qiita.com/myzw1mt3/items/8631d4615509119851a4)

## 残タスク
- [ ] Implement class of Notifier
- [ ] Basic settings

## 画面キャプチャ
No images

2024-06-09 13:36 UTC, Haru-Kobayashi073 reviewed
@aoiorio 
以下修正依頼です！
下二つは細かいけど、大事だから見てみてほしい！

- LocaleViewModelについて
- home_screen.dartファイルでの文字列を使用した現在の言語設定判断について
- home_screen.dartファイルでの多言語対応用の変数について

コメント続く...

2024-06-09 14:29 UTC, Haru-Kobayashi073 requested changes
@aoiorio 
こちら

2024-06-09 14:29 UTC, Haru-Kobayashi073 commented on lib/presentation/social_mobile.dart
> +    final currentLocale = ref.watch(localeViewModelProvider);
この部分でLocaleViewModelが呼び出されて欲しくない
### 理由
- 本来ViewModelはひと画面につき一つ存在する、その画面に関するデータの状態を限りなく無駄がない状態にして、Viewに渡す役割のもの
  - だけど、LocaleViewModelは`social_mobile.dart`でも参照されていることから、ViewModelというよりGlobalStateになる
    - だから、この部分を下記のコメントに合わせて修正してほしい！そしたらあおいちゃんもスッキリするはず
  - またViewModelという存在をもう少しRiverpod likeにしたいためViewModelを無くそうと思う（[目指す参考](https://zenn.dev/oke331/articles/3db9041111ddff#discuss)）
  - これで、どのファイルから呼び出されても違和感がなくなるはず

### 提案

1. presentationフォルダ直下に、グローバルな状態を管理するクラスを格納できるproviderフォルダを作成する
2. 新しく`locale_service.dart`などファイルを作成し、LocaleViewModelのコードを丸々移動させる
3. LocaleViewModelクラスをファイル名に合わせたものに修正する
4. 呼び出し先も名称やインポート文を修正
5. 完了🎉

2024-06-09 14:29 UTC, Haru-Kobayashi073 commented on lib/presentation/home/home_screen.dart
> +                  if (currentLanguage == 'English') {
### なぜ文字列をあまり使用しない方が良いか

- タイプミス(まああまりない)
- 今後の仕様変更での見落とし(めっちゃある)

下のように書くと、`'English'`っていうハードコードの見落としの怖さがなくなる

### 提案

1. home_screen.dartにNotifierではなく、localeViewModelをただ呼び出す
`final localeState = ref.watch(localeViewModelProvider);`
2. 条件文を適したものに変える

```suggestion
                  if (localeState == AppLocale.en) {
```

2024-06-09 14:29 UTC, Haru-Kobayashi073 commented on lib/presentation/home/home_screen.dart
> +    final settingLanguageButtonText =
### 多言語対応用で、変数を使っていたり、そのまま書いていたりする点について

他の場所でも使えるような共通化された変数を作ってほしいです
i18n = internationalizationの略

### 提案

1. 以下のように定義する
```
final socialMobilePageI18n = translations.socialMobilePage;
final settingLanguageTitle = translations.settings.language.title;

.
.
.

Text(settingLanguageTitle),
Text(socialMobilePageI18n.pushExplanation.title),
Text(socialMobilePageI18n.changeLanguage.title),
```

のように！いかがですか？

他の場所で呼び出していないような部分を使ってる場合は、そのまま変数に格納(settingLanguageTitleとか)
色々な位置で同じような呼び出し方をしている場合は、共通化できる部分だけ共通化

2024-06-13 09:32 UTC, aoiorio commented on lib/presentation/home/home_screen.dart
> +                  if (currentLanguage == 'English') {
提案ありがとうございます！
そこで、質問なのですがif文の中に
```dart
if (localeState == AppLocale.en) {
  ref
      .read(localeServiceProvider.notifier)
      .changeLocale(AppLocale.ja);
} else {
  ref
      .read(localeServiceProvider.notifier)
      .changeLocale(AppLocale.en);
}
```
[こちらです！](https://github.com/KDG-Develop-Hub/social-mobile/pull/10/files#diff-e23467e91934cda0799a45eed2b083de70d234735ad02b35492cd1f7a5e25d58R43-R52)

このようにnotifierを呼び出したコードを書いたのですが、これは大丈夫でしょうか？

2024-06-13 10:24 UTC, Haru-Kobayashi073 commented on lib/presentation/home/home_screen.dart
> +                  if (currentLanguage == 'English') {
@aoiorio 
一旦それでOKです！

2024-06-13 12:57 UTC, aoiorio commented
@Haru-Kobayashi073 

conflictの修正完了しました！
よろしくお願いします！

2024-06-13 13:27 UTC, Haru-Kobayashi073 approved these changes
LGTM !

2024-06-13 13:30 UTC, merged