BottomNavigationBarの実装
KDG-Develop-Hub/social-mobile pull request #15
Opened 2024-06-11 15:54 UTC by kiichi7580

## 対応したこと

- ボトムナビゲーターバーを作成

- riverpodで状態管理

- ボトムナビゲーションバーに使用するsvg画像ソースを追加

- genでdartコードにコンバートして使用

## 対応 Issue

- #5 

## 関連資料

[go_routerの使い方](https://www.youtube.com/watch?v=9lRpNOwHH4Y&t=180s)

[Genでdartコードにコンバートする方法](https://www.kamo-it.org/blog/flutterGen/)

## レビューして欲しいこと

- svg画像ソースのファイル名、各画面のファイル名、ウィジェット名をボトムナビゲーションの項目に合わせて、そのまま命名したが、変えた方が良いか？

- 各ページのフォルダを作成し、その直下にファイルを配置するか？

## 画面キャプチャ

https://github.com/KDG-Develop-Hub/social-mobile/assets/130330354/b0e76146-7777-4840-9073-857d2415dd49

2024-06-12 16:46 UTC, Haru-Kobayashi073 requested changes
@kiichi7580 
事前に伝えておいた方が良かったことが多くて申し訳なかったけれど、
コメントについてはなんでも聞いてね！

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on lib/presentation/bottom_navigation.dart
> +final bottomNavigationIndexProvider = StateProvider<int>((ref) => 0);
StateProviderは非推奨なので、あまり使いたくないです！
`bottom_navigation_notifier.dart`ファイルを作成して、早速Notifierを使ってみよう！
indexの値を変えるメソッドをnotifierの中に実装してみよう！

詰まったらいつでも聞いてね

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on lib/presentation/bottom_navigation.dart
> +final appRouter = GoRouter(
GoRouterのコードは、`bottom_navigation.dart`ファイルに記述するのではなく、`utils/routes/`フォルダなどを作成し、その下に`router.dart`ファイルなどを作成しましょう！
今後プロジェクトに参加するメンバーが`bottomNavigationウィジェットのページにGoRouterがあるの気づかなかった`などなるのを防ぐためです！

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on lib/presentation/bottom_navigation.dart
> +          fontWeight: FontWeight.bold,
## 文字スタイルや色はプロジェクト内に定義されたものを使いましょう

他のファイルを見ると参考があります！例えば、`text_field_widget.dart`

ただ、きいちのブランチがdevelopブランチ(最新のリポジトリ)と比べて古いようなので、
developブランチの情報を`feature/bottom-navigation-bar`ブランチに加えましょう！
これをしないと、`text_field_widget.dart`ファイルが見れません

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on lib/presentation/bottom_navigation.dart
> +            icon: index == 0
この部分は、押されたタブのアイコンを切り替えていると思うんだけど、この部分をもっとスマートに実装する方法があります！
それはBottomNavigationBarウィジェットを使わずに[NavigationBarウィジェット](https://zenn.dev/urasan/articles/e9b18c47d1747d)を使うことなんだよね
そしたら、押された時のアイコンをAssetに追加する必要もなくなるはず👍🏻

記事を見てみて！作りたかったものが載っていると思うから
[これもめっちゃおすすめ！！](https://zenn.dev/flutteruniv_dev/articles/stateful_shell_route)

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on pubspec.yaml
> +  flutter_gen_runner: ^5.5.0+1
**パッケージの追加に関してTips**
パッケージをyamlに記述する際に、dev_dependenciesを活用しよう！
普通のdependenciesに書かなければならないものとdev_dependenciesに書かなければならないものとあるので気をつけること

dev_dependenciesについて調べたり、[これ](https://qiita.com/kenta4327/items/ac367751b4b75a33f489)を見ればわかるかも

2024-06-12 16:46 UTC, Haru-Kobayashi073 commented on lib/presentation/home/apude_screen.dart
> +class ApudeScreen extends StatelessWidget {
## 命名について
命名についてめっちゃ迷うのわかる
これはむずい
だから一旦はこれで良いことにして、今後必要な際に変えていこう👍🏻

2024-06-13 00:53 UTC, kiichi7580 commented on pubspec.yaml
> +  flutter_gen_runner: ^5.5.0+1
そうなんだ！全然知らんかったわ

2024-06-13 08:58 UTC, kiichi7580 commented on lib/presentation/bottom_navigation.dart
> +            icon: index == 0
めっちゃ参考になる記事を送っていただきありがとうございます！

2024-06-13 12:36 UTC, Haru-Kobayashi073 approved these changes
LGTM！

2024-06-13 12:37 UTC, merged