💡 Update Locale with SharedPreferences
KDG-Develop-Hub/social-mobile pull request #23
Opened 2024-06-20 07:40 UTC by aoiorio

## 対応したこと
- Localeを初回起動時は端末の言語設定に基づき言語を設定する featureを実装しました
   - 言語を変えるボタンを押すと変えた言語のLanguageCode(e.g. en, ja)がSharedPreferencesの"languageCode"というKeyに保存されます
   - 次回以降、アプリを再起動してもその言語設定が残っている状態になります
- SocialMobileをStatefulHookConsumerWidgetにしました

## 対応 Issue
#13 

## 関連資料
- [Is there a way to load async data on InitState method?](https://stackoverflow.com/questions/51901002/is-there-a-way-to-load-async-data-on-initstate-method)
- [How to get the locale from user's smartphone without context](https://tools.bigwave.biz/notes/blog/posts/flutter_retrieve_locale_info)

## 残タスク
Nothing Maybe...

## 画面キャプチャ
Nothing

2024-06-21 10:36 UTC, Haru-Kobayashi073 commented on lib/presentation/social_mobile.dart
> +  void initState() {
initStateを使いたくなると思うけど、flutter_hooksパッケージのuseEffectを使用すれば、StatefulWidgetを使用せずにinitStateと同じことができます！

2024-06-23 17:31 UTC, Haru-Kobayashi073 requested changes
@aoiorio 
こちら四点の確認お願いします！

2024-06-23 17:31 UTC, Haru-Kobayashi073 commented on lib/presentation/social_mobile.dart
> +  void initState() {
initStateを使いたくなると思うけど、flutter_hooksパッケージのuseEffectを使用すれば、StatefulWidgetを使用せずにinitStateと同じことができます！

2024-06-23 17:31 UTC, Haru-Kobayashi073 commented on lib/presentation/provider/shared_preferences_service.dart
> +    ref.watch(sharedPreferencesProvider).setString(key, value);
providerを監視目的ではなく、メソッドを呼び出す目的に使う際は、`watch`ではなく、`read`を使いましょう！
理由などは[こちら](https://qiita.com/yuto_swift_flutter/items/39ebce2fcd561ea01898#readwatch%E3%81%AE%E4%BD%BF%E3%81%84%E5%88%86%E3%81%91%E3%82%92%E8%80%83%E3%81%88%E3%82%8B)

2024-06-23 17:31 UTC, Haru-Kobayashi073 commented on lib/presentation/provider/locale_service.dart
> +        .setStringValue(key: 'languageCode', value: newLocale.name);
`SharedPreferencesKey`クラスなどを作成して、`lib/utils/routes/routes.dart`ファイルを参考に文字列のkeyを定数として定義して使い回しましょう！！
`languageCode`,`ja`,`en`など

2024-06-23 17:31 UTC, Haru-Kobayashi073 commented on lib/presentation/provider/locale_service.dart
> +        .read(sharedPreferencesServiceProvider.notifier)
```
ref.read(sharedPreferencesServiceProvider.notifier)
```
上記の部分を何度か使用しているので、下記のように共通化して使用するのはどうでしょう？
```
SharedPreferencesService get sharedPreferencesService =>
      ref.read(sharedPreferencesServiceProvider.notifier);
```

2024-06-24 01:08 UTC, aoiorio commented
@Haru-Kobayashi073 
修正いたしました！お時間ある時にご確認ください！

2024-06-24 03:30 UTC, Haru-Kobayashi073 submitted a review, later dismissed
@aoiorio 
一点コメントしましたが、細かいので、修正終わったら、マージしておっけいです！

2024-06-24 03:30 UTC, Haru-Kobayashi073 commented on lib/presentation/provider/shared_preferences_config.dart
> +  static const languageCodeKey = 'languageCode';
細かいですが、クラス名で`Key`と識別子があるので、プロパティ名から`Key`を外すと綺麗かも！

2024-06-24 04:28 UTC, Haru-Kobayashi073 approved these changes
LGTM!

2024-06-24 04:31 UTC, merged