ProfileページのUI作成
KDG-Develop-Hub/social-mobile pull request #26
Opened 2024-07-10 15:59 UTC by kiichi7580

## 対応したこと

- ProfileページのUI作成 

  - プロフィールのヘッダー部分

  - タブ

## 対応 Issue

- #25 

## 関連資料

- [ユーザーアイコンの部分](https://note.com/flutter_hiiisan/n/n2f7a8830db4f)

- [タブの実装](https://www.kamo-it.org/blog/25/)

## レビューして欲しい観点

- タブの中身のつぶやきとかは、別のタスクで実装する感じだよね？

- SafeAreaでpaddingを設定するか

- テキストスタイルがfigmaの仕様とずれてしまっているところがちょいちょいある

  例えば、ユーザー名の部分は、legacy/headingがどこにあるのかわからず代わりのスタイルで一旦実装したが、figmaの仕様通にするにはどうすればいいか

<img width="569" alt="スクリーンショット 2024-07-11 0 44 15" src="https://github.com/KDG-Develop-Hub/social-mobile/assets/130330354/1cfe1183-628b-494c-81d9-7efc3dda46dc">

## 画面キャプチャ

![simulator_screenshot_D429B7D2-B689-40D8-860B-0122B3375927](https://github.com/KDG-Develop-Hub/social-mobile/assets/130330354/6ac9e8dd-ea83-4846-aace-9313323feb0e)

2024-07-12 15:10 UTC, Haru-Kobayashi073 commented
@kiichi7580 
> タブの中身のつぶやきとかは、別のタスクで実装する感じだよね？

そうです！
<br>

> SafeAreaでpaddingを設定するか

現状は必要なさそうに感じますが、どこが気になりました？
<br>

> テキストスタイルがfigmaの仕様とずれてしまっているところがちょいちょいある

現在修正してもらってます！

2024-07-12 15:21 UTC, Haru-Kobayashi073 requested changes
@kiichi7580 
コメントしましたので、ご確認お願いします！

2024-07-12 15:21 UTC, Haru-Kobayashi073 commented on lib/presentation/profile/profile_screen.dart
> +  Widget buildProfileHeader(BuildContext context) {
**以下の色々な理由からメソッドではなく、クラス単位でコンポーネントは分けるようにしましょう！**

- パフォーマンスの最適化が可能（constコンストラクタ、より細かい範囲でのrebuild）
- 異なるWidgetを切り替えるときmethodは以前の状態を再利用することがあるが、classにすることでリソースが正しく処理されるようになる
- ホットリロードが最適に動く
- devtoolでWidget TreeにClass Widgetが表示されるので画面に描画されているレイアウトがわかりやすくなる
- contextを引数で渡す必要がなくなる
などなど、、（[参考](https://qiita.com/b4tchkn/items/8d25e2a5c84c49b7848c)）

2024-07-12 15:21 UTC, Haru-Kobayashi073 commented on lib/presentation/profile/profile_screen.dart
> +        tab(context: context, tabName: 'つぶやき'),
**日本語文字列は忘れず多言語対応をお願いします！**
他の部分も合わせてお願いします！

2024-07-12 15:21 UTC, Haru-Kobayashi073 commented on lib/presentation/profile/profile_screen.dart
> +            textStyle: Theme.of(context).textTheme.labelMedium,
プロフィールの編集ボタンに影がついているようなので、`elevation: 0`などを指定して、デザインと同じようにしてください！

2024-07-13 04:37 UTC, kiichi7580 commented
> @kiichi7580
> 
> > タブの中身のつぶやきとかは、別のタスクで実装する感じだよね？
> 
> そうです！
> 
> > SafeAreaでpaddingを設定するか
> 
> 現状は必要なさそうに感じますが、どこが気になりました？
> 
> > テキストスタイルがfigmaの仕様とずれてしまっているところがちょいちょいある
> 
> 現在修正してもらってます！

了解です！

> > SafeAreaでpaddingを設定するか
> 
> 現状は必要なさそうに感じますが、どこが気になりました？

大丈夫です！

今、外出中なので後ほど対応します！

2024-07-14 07:13 UTC, kiichi7580 commented on lib/presentation/profile/profile_screen.dart
> +  Widget buildProfileHeader(BuildContext context) {
そうなのか！たしかにcontextを引数で渡しまくるのどうなのかなと思ってたけど、classに分ければよかったんだね！

2024-07-16 14:58 UTC, Haru-Kobayashi073 approved these changes
LGTM!!

2024-07-16 15:01 UTC, merged