Postコンポーネントの実装
KDG-Develop-Hub/social-mobile pull request #27
Opened 2024-07-14 16:08 UTC by Haru-Kobayashi073

## 対応したこと

- Postコンポーネントの実装
- ランダムな文字列を返す関数を実装
- モック化したPostリポジトリの実装
- 生成されたファイル(g.dart,freezed.dart,gen.dart)を静的リンターの対象外に設定

## 対応 Issue

- #18 

## 関連資料

特になし

## 残タスク

- [ ] Postの投稿日時のフォーマットをどうするか
- [ ] リアクションボタンとリプライボタンの実装
- [ ] メニューの実装

## 画面キャプチャ

<img width="456" alt="スクリーンショット 2024-07-15 1 07 50" src="https://github.com/user-attachments/assets/e5fbe2b7-c248-4a32-a768-2886b4ef60b9">

2024-07-22 12:01 UTC, Haru-Kobayashi073 commented
@imeankenshin @shi0n0 @Ry8Sg2i @kiichi7580 @aoiorio 
日付のフォーマット方法のみMTGで相談予定ですが、それ以外は完了いたしましたので、ご確認お願いします！

2024-07-24 06:02 UTC, Haru-Kobayashi073 commented
@imeankenshin @shi0n0 @Ry8Sg2i @kiichi7580 @aoiorio
完了したので、確認お願いします！

2024-07-24 14:49 UTC, Ry8Sg2i submitted a review, later dismissed

2024-07-27 13:06 UTC, aoiorio submitted a review, later dismissed
LGTM!

2024-07-28 09:08 UTC, shi0n0 submitted a review, later dismissed
LGTM👍

2024-07-28 09:17 UTC, imeankenshin requested changes
自分でデザインしておいてちょっと不満を言うのは申し訳ないけど、ちょっとボトムシートの横の余白が大きすぎるなぁ🙄
たった今Figmaのデザインを更新したからそれを反映させたらLGTM行けるね！

2024-07-29 03:41 UTC, kiichi7580 submitted a review, later dismissed

2024-07-30 07:18 UTC, imeankenshin approved these changes
LGTM!

2024-07-30 09:03 UTC, merged