💡 Create Share Post Feature
KDG-Develop-Hub/social-mobile pull request #34
Opened 2024-08-01 13:05 UTC by aoiorio

## 対応したこと
- I created sharing post feature!!
- こちらが共有した後の文章です。
```
{Username} posted "{Post Sentence}". (e.g. Atom posted "Hello there".)
```

## 対応 Issue
- #30 

## 関連資料
[Share Feature](https://qiita.com/MLLB/items/ae052699bfe3b852fa6c)

## 残タスク
Nothing

## 画面キャプチャ
| Dark mode | Normal mode |
| ---- | ---- |
| <img src="https://github.com/user-attachments/assets/dec44d38-eaa8-492d-84ce-8cdefef789a9" width=200> | <img src="https://github.com/user-attachments/assets/a5c9ea82-f2f2-43be-addb-ad4602233510" width=200> |

2024-08-02 03:39 UTC, aoiorio commented
@Haru-Kobayashi073 
確認お願いいたします！

2024-08-06 08:32 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/post_menu_bottom_sheet.dart
> +                  await Share.share(
@aoiorio 
Shareクラスはここで呼ばず、helpersディレクトリ配下にファイルを作成し、クラスを作成して、呼び出しましょう！
これからメソッドのカスタマイズをしていく上で、コードが肥大化する前に切り離したいからです！

2024-08-06 08:33 UTC, Haru-Kobayashi073 requested changes
@aoiorio 
確認が遅くなってすみません！
コメント一点のみ確認をお願いします！

2024-08-06 15:36 UTC, aoiorio commented on lib/presentation/components/post_card/post_menu_bottom_sheet.dart
> +                  await Share.share(
@Haru-Kobayashi073 
レビューありがとうございます！
修正いたしましたので、ご確認いただけると嬉しいです！

2024-08-06 15:57 UTC, Haru-Kobayashi073 commented on lib/utils/helpers/share_post.dart
> +
今回の修正だとクラスではなく関数になっているので、以下のようにクラスでカプセル化しましょう！
少し伝えづらいので、今回は、一旦書いちゃいます...!

- 今回このような対応をした理由としては、Shareクラスのメソッドを使用する関数などを一元管理したいからです！

```dart
class ShareService {
  // プライベートコンストラクタでインスタンス化を防ぐ
  ShareService._();

  static Future<void> sharePost(Post post) async {
    await shareText(
      '${post.userName} posted "${post.content}".',
      subject: 'Check out this post!',
    );
  }
}
```

このように呼び出せるかと思います！

```dart
await ShareService.sharePost(post);
```

2024-08-06 15:57 UTC, Haru-Kobayashi073 requested changes
@aoiorio 
意図がうまく伝わってなかったです...!!
コメントの通りに修正してもらうか、アレンジしてもよしです！
変更していただきたです！

2024-08-06 16:12 UTC, aoiorio commented on lib/utils/helpers/share_post.dart
> +
@Haru-Kobayashi073 
コードありがとうございます！！
すみません！文章の理解が足りていませんでした！
修正いたします！

2024-08-06 16:55 UTC, aoiorio commented on lib/utils/helpers/share_post.dart
> +
@Haru-Kobayashi073 
修正いたしました！ご確認よろしくお願いいたします🙇🏼

質問なのですが、`ShareService._();`と`static`は同じインスタンス化を防ぐ事ができると記事に書いてありました。
そこで、プライベートコンストラクタを普通のクラスのように`ShareService();`として定義し、staticはそのままにして実行すると特にエラーも起きずに機能しました。
staticがある場合、この`ShareService._();`は`ShareService();`でも代用できますでしょうか？

こちらが試してみたコードになります。
```dart
class ShareService {
  // NOTE prevent instantiation
  ShareService();

  static Future<void> sharePost(Post post) async {
    await Share.share(
      '${post.userName} posted "${post.content}".',
      subject: 'Wherever, the post will take us',
    );
  }
}

```

### 参考にした記事
- [private constructor](https://note.com/yuh_programming/n/n7e929b66aef6)
- [static](https://zenn.dev/tsukatsuka1783/articles/flutter_various_tips)

よろしくお願いいたします！

2024-08-09 11:41 UTC, Haru-Kobayashi073 approved these changes
ごめん、`ShareService`クラスのファイル名が`share_post.dart`になっていたので、そこだけ修正しました！
LGTM！！

2024-08-09 11:44 UTC, imeankenshin approved these changes
LGTM!

2024-08-09 11:44 UTC, merged