💡 Create Splash Screen
KDG-Develop-Hub/social-mobile pull request #40
Opened 2024-09-17 15:55 UTC by aoiorio

## 対応したこと
- Splash Screenを追加しました
- iosでは見ることはできたのですが、androidはエラーが出て確認できませんでした。

## 対応 Issue
#39 

## 関連資料
- [how to implement splash screen](https://zenn.dev/susatthi/articles/20220406-061305-flutter-native-splash)

## 残タスク
nothing

## 画面キャプチャ
<img src="https://github.com/user-attachments/assets/f0c1cd23-827b-4695-b1d8-8b88cf29ac07" width=200>

https://github.com/user-attachments/assets/f9fa0c73-fe26-4758-a16d-22c95bbf3ef1

2024-09-18 08:42 UTC, Haru-Kobayashi073 commented
@aoiorio 

> iosでは見ることはできたのですが、androidはエラーが出て確認できませんでした。

今PRがreadyになってるけれど、この文を見るに、困ってるから何か意見が欲しいとかかなって思ったんだけどどう？

2024-09-18 09:22 UTC, Haru-Kobayashi073 reviewed
@aoiorio

iosでは見ることはできたのですが、androidはエラーが出て確認できませんでした。

今PRがreadyになってるけれど、この文を見るに、困ってるから何か意見が欲しいとかかなって思ったんだけどどう？

2024-09-18 13:49 UTC, aoiorio commented
@Haru-Kobayashi073 

お疲れ様です！
> 今PRがreadyになってるけれど、この文を見るに、困ってるから何か意見が欲しいとかかなって思ったんだけどどう？

すみません〜〜！readyになってました〜！draftに変えます〜！

調べてみたところ、share_plusはjdkのバージョンが17以上でなければandroidをbuildできないことが原因でのエラーだと発覚しました。
share_plusを削除すると、build自体はできますが、下記の画像のようになってしまいます。

この問題の解決法のヒントなど、ありましたら教えていただけると嬉しいです！
また明日も色々検索するつもりです！

<img src="https://github.com/user-attachments/assets/66260fbc-efff-4e63-bee4-4cbcab8e16c9" width=200>

2024-09-21 03:54 UTC, aoiorio commented
@Haru-Kobayashi073 
お疲れ様です！
iosの方のsplash screenを手動で大きくしたので、レビューをお願いいたします！

2024-09-21 07:08 UTC, imeankenshin requested changes
ちょいとAndroid版のロゴが小さく見える。これは変更可能ならもう一回り大きめにしたいね🤔。理想としては、ロゴの幅が画面の幅の8割くらい？

2024-09-21 12:18 UTC, aoiorio commented
@imeankenshin 
レビューありがとうございます！
やはり、小さいですよね〜。
Androidの方なのですが、splash screenを設定するとき自動でアイコンが丸く切り抜かれる様で、今のsplash screenが丸に被らない最大の大きさです😭。。。
iOSの方のサイズは大丈夫でしょうか？

2024-09-21 12:51 UTC, Haru-Kobayashi073 commented
@aoiorio 
あー確かにそうか
じゃあ、iOSの方を少し小さく出来る?👀
何度もごめんね🙏🏻

2024-09-21 13:04 UTC, aoiorio commented
@Haru-Kobayashi073 
了解しました！！全然大丈夫です！！

2024-09-21 13:19 UTC, aoiorio commented
@Haru-Kobayashi073 @imeankenshin 
iosのsplash screenのサイズを調整したので、レビューをお願いします！

2024-09-21 13:30 UTC, Haru-Kobayashi073 approved these changes
@aoiorio 
完璧です！
LGTM！！

2024-09-21 13:46 UTC, imeankenshin commented
@aoiorio LGTM!

2024-09-21 13:47 UTC, imeankenshin approved these changes
LGTM!

2024-09-21 14:26 UTC, merged