Feature/post UI
KDG-Develop-Hub/social-mobile pull request #55
Opened 2024-11-14 09:27 UTC by Ry8Sg2i

## 対応したこと

homeにbutton追加
つぶやきページとそのルート作成

## 対応 Issue

https://github.com/KDG-Develop-Hub/social-mobile/issues/29

## 画面キャプチャ

<div style="display: flex;">
  <img src="https://github.com/user-attachments/assets/7a282910-19f1-412e-871d-9ecdcc90a17c" alt="" width="350" style="margin-right: 10px;"/>
  <img src="https://github.com/user-attachments/assets/09bdea8c-a9ac-4ac1-b63d-95881a610dc8" alt="シミュレーター" width="350"/>
</div>

2024-11-17 03:03 UTC, Haru-Kobayashi073 requested changes
@Ry8Sg2i 
一旦修正お願い！

2024-11-17 03:03 UTC, Haru-Kobayashi073 commented on lib/presentation/home/home_screen.dart
> +        backgroundColor: const Color(0xFF386666),
定数の色を使って設定して欲しい！

2024-11-17 03:03 UTC, Haru-Kobayashi073 commented on lib/utils/routes/app_router.dart
> +final postNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'post');
これは、BottomNavigationBarの要素(home,search,profile,setting)にしか必要ないので消そう！

2024-11-17 03:03 UTC, Haru-Kobayashi073 commented on lib/presentation/home/post/post_screen.dart
> +                    hintText: '今日の天気はそこまでよくないな。カフェ行こうと思ったけど遠慮しとこうかな？',
これは、例えの話なのでhintTextじゃなくても大丈夫！

2024-11-17 03:03 UTC, Haru-Kobayashi073 commented on lib/presentation/home/post/post_screen.dart
> +                    SizedBox(
このボタンは一旦削除でお願い！
バージョン２でリリース予定

2024-11-18 04:58 UTC, Ry8Sg2i commented on lib/presentation/home/home_screen.dart
> +        backgroundColor: const Color(0xFF386666),
done

2024-11-18 04:58 UTC, Ry8Sg2i commented on lib/utils/routes/app_router.dart
> +final postNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'post');
done

2024-11-18 04:58 UTC, Ry8Sg2i commented on lib/presentation/home/post/post_screen.dart
> +                    SizedBox(
done

2024-11-18 05:00 UTC, Ry8Sg2i commented on lib/presentation/home/post/post_screen.dart
> +                    hintText: '今日の天気はそこまでよくないな。カフェ行こうと思ったけど遠慮しとこうかな？',
done

2024-11-18 05:10 UTC, Haru-Kobayashi073 approved these changes
LGTM!!!

2024-11-18 05:11 UTC, merged