[Post Component] 削除の再確認モーダル・報告モーダルの実装
KDG-Develop-Hub/social-mobile pull request #67
Opened 2024-11-21 07:44 UTC by kiichi7580

## 対応したこと

- つぶやきの削除の確認モーダルと通報モーダルを作成
- モーダルが複数あったのでベースとなるモーダルをコンポーネント化
- リアクション、コメントなどがついていないシンプルなつぶやきカード(SimplePostCard)を作成

## 対応 Issue

- #31 

## 関連資料

- ListTile内のleadingのウィジェットとtitleのウィジェット間を狭める方法

[ListTile の「leading」と「title」の間の余白を減らすにはどうすればいいですか?](https://stackoverflow.com/questions/53474168/how-to-reduce-the-margin-between-leading-and-title-for-listtile-flutter)

[RadioListTileについて](https://fluttoco.com/flutter-radio-list-tile/)

## 残タスク

- ラジオボタンのプロバイダーはまだ作成してない
- 削除後・通報後の処理もまだ実装していない

## レビューして欲しい観点

- ファイル名・クラス名などは適切でわかりやすいかどうか

## 聞きたいこと

- モーダルシートで共通化できそうな部分をコンポーネント化したが良いか？

- PostCardの方もコンポーネント化するか？

- モーダル内の文言を多言語かするか？

- UI面
  - 削除モーダルの「削除されたつぶやきは、30日後に完全に削除されます。」のテキストのスタイルがfigma上に載っていなかったが、スタイルを指定しないという認識であっているか？

  - ラジオボタンの部分をRadioListTileウィジェットを使用して実装したが良いか？
  →使用した理由としては、シンプルに使えそうだと思ったから

- UIしか作成していないが、モーダル内のプロバイダーまで作成する必要があるか？

## 画面キャプチャ

| つぶやき削除確認モーダル | つぶやき報告モーダル |
| -- | -- |
| <img src="https://github.com/user-attachments/assets/1f47d074-50e3-4077-874f-a8c0a5079dc7" width=200> | <img src="https://github.com/user-attachments/assets/60715db6-d261-415b-ad16-5bb8de5c66b2" width=200> |

2024-11-23 05:27 UTC, Haru-Kobayashi073 commented
> モーダルシートで共通化できそうな部分をコンポーネント化したが良いか？

して欲しいです！
例えば、引数で以下を持たせます
なるべくコンポーネントを呼び出す側が書くコードが少なくなるようにしてください！
**ただ、PostMenuBottomSheetはCustomBottomSheetコンポーネントを使用しないでください
理由は、あまり共通点がないからです！**

- required
  - 一番上のアイコンのパス
  - タイトルのテキスト
  - 削除するや通報するボタンの処理

- optional
  - 説明文(削除モーダルのみにあるから)
  - content(通報モーダルのみラジオボタンが必要だから)

- 共通化する部分
  - アイコンの位置・大きさ
  - タイトルの位置・スタイル
  - 説明文の位置・スタイル
  - PostCardの位置
  - やっぱやめるボタンのデザイン・位置・処理内容
  - 通報するや削除するボタンの位置・スタイル
  - など

> PostCardの方もコンポーネント化するか？

はい！今回はボタンがないバージョンのPostCardが必要になると思うので、作ってもらったSimplePostCardでいい感じです！ただわかりやすく名前を変えるとするならば、`ContentsOnlyPostCard`などだと直感でわかりやすいかなと！

> モーダル内の文言を多言語かするか？

お願いします！
もちろんポストカード内の文字は投稿者に依存するので、多言語対応はいりません

UI面



> 削除モーダルの「削除されたつぶやきは、30日後に完全に削除されます。」のテキストのスタイルがfigma上に載っていなかったが、スタイルを指定しないという認識であっているか？

ミスっぽいので直してもらいました！

> ラジオボタンの部分をRadioListTileウィジェットを使用して実装したが良いか？
> →使用した理由としては、シンプルに使えそうだと思ったから

使用して、デザイン通りのUIになるのであれば、使って欲しいです！

> UIしか作成していないが、モーダル内のプロバイダーまで作成する必要があるか？

必要ないです！
ただ、Radio Buttonは複数のうち一つだけを選択できるようにHooksやらを使って実装して欲しいです！

2024-11-24 14:07 UTC, kiichi7580 commented
@Haru-Kobayashi073 
レビューしていただいたところ修正しましたので、ご確認よろしくお願いします。
足りない点あれば、再度ご指摘ください。

2024-11-24 17:19 UTC, Haru-Kobayashi073 requested changes
@kiichi7580 
全体的にいい感じです！ありがとう！
細かいところ修正お願いします！


> ボトムシート内のpadding関連をどうするか

こちらは、解決しましたか？
もししてない場合詳しく教えて！

2024-11-24 17:19 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/bottom_sheets/custom_bottom_sheet.dart
> +    required this.buttonText,
この引数名だと何のボタンのテキストを入力するのか直感でわからないので、わかるようにしましょう！
```suggestion
    required this.submitButtonText,
```

2024-11-24 17:19 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/bottom_sheets/custom_bottom_sheet.dart
> +    required this.onPressedButton,
こちらも何の処理を書くのか直感でわかりやすくするために、変更しましょう！
```suggestion
    required this.onPressedSubmit,
```

2024-11-24 17:19 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/bottom_sheets/custom_bottom_sheet.dart
> +  final void Function()? onPressedButton;
完了処理は必ずnonNullで(空ではなく)あって欲しいので、`?`は消しましょう！

2024-11-24 17:19 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/bottom_sheets/custom_bottom_sheet.dart
> +                onPressed: () {},
戻るボタンはどのSheetでも処理は同じだと思うので、直接書いてあげましょう！
```suggestion
                onPressed: () {
                  context.pop();
                },
```

2024-11-24 17:19 UTC, Haru-Kobayashi073 commented on lib/presentation/components/post_card/contents_only_post_card.dart
> +      margin: const EdgeInsets.fromLTRB(16, 0, 16, 0),
わかりやすいようにfactoryメソッドを使いましょう！
以下は横に16ずつという意味です
```suggestion
      margin: const EdgeInsets.symmetric(horizontal: 16),
```

2024-11-25 07:29 UTC, kiichi7580 commented
@Haru-Kobayashi073 
> ボトムシート内のpadding関連をどうするか
> 
> こちらは、解決しましたか？
> もししてない場合詳しく教えて！

消し忘れです。すみません。こちら解決しております！

2024-11-25 07:35 UTC, kiichi7580 commented on lib/presentation/components/post_card/bottom_sheets/custom_bottom_sheet.dart
> +    required this.buttonText,
確かにそうですね！修正します！

2024-11-25 07:45 UTC, Haru-Kobayashi073 approved these changes
完璧！
LGTM!!!

2024-11-25 08:07 UTC, kiichi7580 commented
ご確認ありがとうございます！
マージいたします！

2024-11-25 08:07 UTC, merged